{"url": "https://www.brainyquote.com/authors/a"}
{"url": "https://www.brainyquote.com/authors/u"}
{"url": "https://www.brainyquote.com/authors/z"}
{"url": "https://www.brainyquote.com/authors/y"}
{"url": "https://www.brainyquote.com/authors/x"}
{"url": "https://www.brainyquote.com/authors/v"}
{"url": "https://www.brainyquote.com/authors/w"}
{"url": "https://www.brainyquote.com/authors/s"}
{"url": "https://www.brainyquote.com/authors/t"}
{"url": "https://www.brainyquote.com/authors/q"}
{"url": "https://www.brainyquote.com/authors/r"}
{"url": "https://www.brainyquote.com/authors/p"}
{"url": "https://www.brainyquote.com/authors/m"}
{"url": "https://www.brainyquote.com/authors/n"}
{"url": "https://www.brainyquote.com/authors/k"}
{"url": "https://www.brainyquote.com/authors/l"}
{"url": "https://www.brainyquote.com/authors/i"}
{"url": "https://www.brainyquote.com/authors/g"}
{"url": "https://www.brainyquote.com/authors/j"}
{"url": "https://www.brainyquote.com/authors/d"}
{"url": "https://www.brainyquote.com/authors/e"}
{"url": "https://www.brainyquote.com/authors/c"}
{"url": "https://www.brainyquote.com/authors/b"}
{"url": "https://www.brainyquote.com/authors/o"}
{"url": "https://www.brainyquote.com/authors/h"}
{"url": "https://www.brainyquote.com/authors/f"}
